- name: "Building Docker Image"
  hosts: build
  become: true
  vars:
    git_url: https://github.com/Jisjo/Docker_python_flask_helow-world.git
    docker_user: "jisjo"
    docker_password: "xxxxxxxxxxxxxxxxxxxxxxxxxx"
    image_name: "jisjo/devops-flaskapp"
  tasks:
    
    - name: "Build - Package Installation"
      yum:
        name:
          - docker
          - git
          - python2-pip
        state: present
            
    - name: "Build - Sarting Docker Service"
      service:
        name: docker
        state: restarted
        enabled: true
            
    - name: "Build - Installing Docker Client For Python"
      pip:
        name: docker-py
        state: present
            
    - name: "Build - Cloning Github Repository {{ git_url }}"
      git:
        repo: "{{ git_url }}"
        dest: "/var/flaskapp/"
      register: git_status      

    - debug:
        var: git_status
                  
    - name: "Build - Login to remote Repository"
      when: git_status.changed == true
      docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"

    - name: "Build - Docker image from Dockerfile"
      when: git_status.changed == true
      docker_image:
        build:
          path: "/var/flaskapp/"
        name: "{{image_name}}"
        tag: "{{ item }}"
        push: yes
        source: build
      with_items:
        - "latest"
        - "{{ git_status.after }}"
